openapi: 3.1.0
info:
  contact:
    email: https://github.com/saviynt
    name: Saviynt Developers Team
  description: "Transporting Packages: https://docs.saviyntcloud.com/bundle/EIC-Admin-AMS/page/Content/Chapter07-General-Administrator/Transporting-Packages.htm"
  title: Saviynt Transport API
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: Transport
paths:
  /ECM/api/v5/exportTransportPackage:
    post:
      description: This API creates a compressed file containing objects specified
        for T2P migration.
      operationId: exportTransportPackage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExportTransportPackageRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportTransportPackageResponse'
          description: OK
      summary: Export Transport Package
      tags:
      - Transport
  /ECM/api/v5/importTransportPackage:
    post:
      description: |-
        This API imports a compressed file containing objects specified for T2P migration.

        Supported objects:

        savRoles, emailTemplate, roles, analyticsV1, analyticsV2, globalConfig, workflows, connection, appOnboarding, userGroups, scanRules, organizations, securitySystems
      operationId: importTransportPackage
      requestBody:
        content:
          application/json:
            examples:
              Example 1:
                value:
                  updateuser: admin
                  packagetoimport: /saviynt_shared/testexport/transportPackage/transport_admin_2023-01-13_10-19-11(UTC).zip
                  businessjustification: test
            schema:
              $ref: '#/components/schemas/ImportTransportPackageRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportTransportPackageResponse'
          description: OK
      summary: Import Transport Package
      tags:
      - Transport
  /ECM/api/v5/transportPackageStatus:
    get:
      description: |-
        This API obtains the status of the transport request (import, export, or transfer), and helps in confirming whether the transport was completed successfully or failed.

        Note: This API returns the status of only those requests that have been processed using the Enhanced Transport feature.
      operationId: transportPackageStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransportPackageStatusRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransportPackageStatusResponse'
          description: OK
      summary: Transport Package Status
      tags:
      - Transport
components:
  schemas:
    ExportTransportPackageRequest:
      description: ""
      example:
        transportowner: transportowner
        transportmembers: transportmembers
        businessjustification: businessjustification
        environmentname: environmentname
        exportonline: exportonline
        exportpath: exportpath
        updateuser: updateuser
        objectstoexport:
          savRoles:
          - savRoles
          - savRoles
          emailTemplate:
          - emailTemplate
          - emailTemplate
      properties:
        updateuser:
          description: username of the user exporting the package
          type: string
          x-stoplight:
            id: fu9d0rj8la3eo
        transportowner:
          description: (can be true or false) - option to transport owners for selected
            objects
          type: string
          x-stoplight:
            id: kokb7b8w3v3yy
        transportmembers:
          description: can be true or false) - option to transport members for selected
            objects such as SAV role
          type: string
          x-stoplight:
            id: xto5ohy0603ys
        exportonline:
          description: (can be true or false) - Determines if package needs to be
            exported online
          type: string
          x-stoplight:
            id: m3zbu3f1s4md4
        exportpath:
          description: (if exportonline is false) - Local path where export package
            will be generated
          type: string
          x-stoplight:
            id: e3mri1ib5patv
        environmentname:
          description: "(if exportonline is true) - Name of the environment which\
            \ can be created at the following path : Admin -> Global Configurations\
            \ -> Misc -> Transport -> Add New Transport"
          type: string
          x-stoplight:
            id: poxj5q3j7zvt7
        businessjustification:
          type: string
          x-stoplight:
            id: po8i7fv2v5rik
        objectstoexport:
          $ref: '#/components/schemas/ObjectsToExport'
      required:
      - exportonline
      - objectstoexport
      title: ExportTransportPackageRequest
      x-stoplight:
        id: bn1ui71jne1we
    ObjectsToExport:
      example:
        savRoles:
        - savRoles
        - savRoles
        emailTemplate:
        - emailTemplate
        - emailTemplate
      properties:
        savRoles:
          items:
            type: string
            x-stoplight:
              id: 2val4wnerkqd2
          type: array
          x-stoplight:
            id: if4npvrn65ly8
        emailTemplate:
          items:
            type: string
            x-stoplight:
              id: cwse89xfavmeq
          type: array
          x-stoplight:
            id: glkjtgi0jiqpt
      title: ObjectsToExport
      x-stoplight:
        id: 9z1hfxvbn0zav
    ExportTransportPackageResponse:
      example:
        msg: msg
        fileName: fileName
        msgDescription: msgDescription
        errorcode: 0
      properties:
        msg:
          type: string
          x-stoplight:
            id: ofd1xk6jm68l1
        fileName:
          type: string
          x-stoplight:
            id: 0mgsqu430jj4s
        msgDescription:
          type: string
          x-stoplight:
            id: mbsk6vd4s85zm
        errorcode:
          type: integer
          x-stoplight:
            id: l5896jtsfm1fy
      required:
      - errorcode
      - msg
      title: ExportTransportPackageResponse
      x-stoplight:
        id: ctaaycs2pwfmd
    TransportPackageStatusRequest:
      example:
        filename: filename
        requestid: requestid
        operation: export
      properties:
        operation:
          description: "enter the type of transport request (export, import, or transfer)"
          enum:
          - export
          - import
          - transfer
          type: string
          x-stoplight:
            id: o6g12n9rxn2t4
        filename:
          description: enter the transport package zip file name in full (including
            the .zip extension)
          type: string
          x-stoplight:
            id: xlnkv5gq8w9ev
        requestid:
          description: (required only if the operation is import) - enter the request
            ID generated during the submission of the import request
          type: string
          x-stoplight:
            id: j82ir7ym6at2m
      required:
      - filename
      - operation
      title: TransportPackageStatusRequest
      x-stoplight:
        id: 7tg0ihg4biemh
    TransportPackageStatusResponse:
      example:
        msg: msg
        msgDescription: msgDescription
        errorCode: 0
      properties:
        msg:
          type: string
          x-stoplight:
            id: ahrsh2vc4m3c7
        msgDescription:
          type: string
          x-stoplight:
            id: 778at054odbjn
        errorCode:
          type: integer
          x-stoplight:
            id: ebuqgop7yv8q6
      title: TransportPackageStatusResponse
      x-stoplight:
        id: xh4kaggchfgoc
    ImportTransportPackageRequest:
      example:
        packagetoimport: packagetoimport
        businessjustification: businessjustification
        updateuser: updateuser
      properties:
        packagetoimport:
          description: Complete path of the package that needs to be imported
          type: string
        updateuser:
          description: username of the user importing the package
          type: string
        businessjustification:
          type: string
      required:
      - packagetoimport
      x-examples:
        Example 1:
          updateuser: admin
          packagetoimport: /saviynt_shared/testexport/transportPackage/transport_admin_2023-01-13_10-19-11(UTC).zip
          businessjustification: test
    ImportTransportPackageResponse:
      example:
        msg: msg
        requestId: requestId
        msgDescription: msgDescription
        errorcode: 0
      properties:
        msg:
          type: string
        requestId:
          type: string
        msgDescription:
          type: string
        errorcode:
          type: integer
      x-examples:
        Example 1:
          msg: success
          requestId: "2490001"
          msgDescription: "Import Requested. If other requests are currently processing,\
            \ your import will begin after they complete. You can call /transportPackageStatus\
            \ API to check the status of your import"
          errorcode: 0
x-stoplight:
  id: nj0buptcpdipb
